title: Mi madre tiene un blog de cocina
description: Blog de cocina, crítica culinaria y golosinas varias
theme:
cayman-blog:
  date_format: "%Y-%m-%d"
author: Javier Díaz Bustamante
author_email: javidbu@gmail.com
twitter:
  username: javidbu
google_analytics: UA-84065359-2
plugins:
  - jekyll-feed