title: Mi madre tiene un blog de cocina
description: Blog de cocina, crítica culinaria y golosinas varias
url: http://mimadretieneunblogdecocina.com
theme:
cayman-blog:
  date_format: "%Y-%m-%d"
author: Javier Díaz Bustamante
author_email: javi@mimadretieneunblogdecocina.com
twitter:
  username: MamaTiene1Blog
instagram:
  username: mimadretieneunblogdecocina
facebook:
  page: MiMadreTieneUnBlogDeCocina
telegram:
  channel: mimadretieneunblogdecocina
google_analytics: UA-84065359-2
plugins:
  - jekyll-feed